name: release
'on':
  workflow_dispatch: null
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: 'echo "::set-output name=today::$(date +''%Y%m%d%M%S'')"'
      - uses: release-drafter/release-drafter@v5
        name: ReleaseDraft
        id: releasedraft
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: '${{ steps.date.outputs.today }}'
          release_name: '${{ steps.date.outputs.today }}'
          body: '${{steps.releasedraft.outputs.content}}'
          draft: false
          prerelease: false
